### ISSUE TITLE
Discord auth returns 401

### ISSUE THREAD

**Issue by benclarkk** [crybapp/api#3]
hi,
when logging in with discord, the web app shows `An error occured while authenticating. Please go home and Login with Discord again`, and the api logs show `POST /auth/discord 401 0.738 ms - 12`.
Console logs:
[console-export-2019-10-15_19-5-5.txt](https://github.com/crybapp/api/files/3730823/console-export-2019-10-15_19-5-5.txt)
My web env:
https://gist.github.com/benclarkk/0795888dd5361dee7e9913aeb8b34ada
My API env:
https://gist.github.com/benclarkk/ba602a40abf25e4dc7f28a481fee0532

**Comment by benclarkk** [comment]
idk if this is a good place to put this but

**Comment by williamsthing** [comment]
Looks like your `DISCORD_OAUTH_ORIGINS` is incorrect. Try `DISCORD_OAUTH_ORIGINS=http://ip:3000`.

Let me know if this works or if you have any other issues!

**Comment by benclarkk** [comment]
I've changed it to `DISCORD_OAUTH_ORIGINS=http://myip:3000`, however it doesn't look like it's fixed the problem :(

**Comment by benclarkk** [comment]
![bruhmoment](https://user-images.githubusercontent.com/46399411/66864799-e0a75280-ef8d-11e9-8674-815daac29665.png)
here's my redirects on discord if that helps.

**Comment by akunim** [comment]
For the life of me I can't figure out why this is happening (something to do with dotenv parsing, or something overwriting the variable? I couldn't find anything), but _process.env.DISCORD_OAUTH_ORIGINS_ keeps returning '1,2' for me, regardless of what I set in the .env file

api/.env
![vOclg8n](https://user-images.githubusercontent.com/13560536/66889124-d8a7dc80-efa6-11e9-8e9e-c0fc6d084dda.png)
api/src/controllers/auth.controller.ts
![7OAZdgA](https://user-images.githubusercontent.com/13560536/66889183-16a50080-efa7-11e9-9973-2ca1e5d64c80.png)
output
![oKT3bJv](https://user-images.githubusercontent.com/13560536/66889199-23c1ef80-efa7-11e9-9fbd-20e85da4fcf7.png)

I fixed it for myself by just changing the name to 'DISCORD_OAUTH_ORIGIN' in the .env file and the auth controller, but that feels kinda kludgy.

**Comment by akunim** [comment]
I'm running it remotely, and I think ben is too. I suspect his issue is the same one I was having.

`DISCORD_OAUTH_ORIGINS` isn't returning the URI from the .env file when auth.controller asks for it, which causes it to return 401 when the origins don't match.

`http://localhost:3000` will work for running locally, but only because it gets pushed to the origins array in the auth controller https://github.com/crybapp/api/blob/master/src/controllers/auth.controller.ts#L12

**Comment by williamsthing** [comment]
I'll try experiment with that to see if there is a better fix available

**Comment by williamsthing** [comment]
Does this fix any issues? https://github.com/crybapp/api/commit/032557e649d61a5a694269930b3ffd30fc41d483 @akunim

**Comment by akunim** [comment]
Still throws the 401 if I don't use a different env variable for setting origins

`process.env.DISCORD_OAUTH_ORIGINS` still seems to be acting strange for me

dumping process.env when api launches, it looks like it's getting set earlier than the rest of the values in the .env file, but I'm not sure the significance of that
![Capture (1)](https://user-images.githubusercontent.com/13560536/66923288-23007c00-efee-11e9-8339-fc33da3f6d83.PNG)


.env file
https://gist.github.com/akunim/76b33d93edcd2b30fe4c16ebe3c24757

**Comment by benclarkk** [comment]
032557e fixes the issue for me, so that's strange. but thanks for the fix @williamsthing.

**Comment by JeDaYoshi** [comment]
Fixed already. For support get to the Cryb Discord server.
